name: matrix
on: 
  issue_comment: 
    types: [created]

jobs:
  build:
    name: Build
    if: contains(github.event.comment.body, 'matrix')
    strategy:
      matrix:
        go-version: [1.12.7]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
