name: Build and test Go

on: 
  issue_comment: 
    types: [created]

jobs:
  build:
    name: Build
    if: contains(github.event.comment.body, 'run tests')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12.7
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.7

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v .
